services:
  - type: web
    name: employee-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_USER
        value: your_db_username
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_SERVER
        value: your_sql_server_ip
      - key: DB_PORT
        value: 1433
      - key: DB_DATABASE
        value: your_database_name